name: Richard Djarbeng
title: Richard Djarbeng's Personal Website
description: Developer | Computer Engineer
theme: jekyll-theme-minimal

permalink: /:categories/:year/:month/:day/:title:output_ext

plugins:
  - jekyll-relative-links

markdown: kramdown
kramdown:
  input: GFM

future: true

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - node_modules/