title: Richard Djarbeng
description: >- 
  Developer and Computer Engineer specializing in web development, 
  machine learning, and IoT devices.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://RDjarbeng.github.io" # the base hostname & protocol for your site
github_username: RDjarbeng
twitter_username: DjarbengRichard
linkedin_username: richarddjarbeng

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Collections
collections:
  projects:
    output: true
sass:
  sass_dir: _sass
  quiet_deps: true