title: Richard Djarbeng- Computer Engineer & Tech leader
description: >- 
  Explore the journey and insights of a Computer Engineer specializing in AI, 
  web development, machine learning, and IoT. Discover cutting-edge tech trends, 
  practical coding tips, and thought-provoking reflections on the evolving 
  world of technology. Occasionally I write personal reflections on the personal section.
keywords: [AI, web development, Internet of Things, machine learning, air quality, IoT, tech trends, coding, engineering]
author: Richard Djarbeng
baseurl: "/RDjarbeng" # the subpath of your site, e.g. /blog
url: "https://RDjarbeng.github.io" # the base hostname & protocol for your site
github_username: RDjarbeng
twitter_username: DjarbengRichard
linkedin_username: richarddjarbeng

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

seo:
  title: "Web, Internet of things and Data -Richard Djarbeng's website"
  description: >-
    Learning journey and reflections of a computer engineer specializing in web development, 
    machine learning, and IoT devices.
  url: "https://rdjarbeng.github.io/RDjarbeng/"
  twitter: DjarbengRichard
  logo: "/favicon.ico"
  theme_color: "#999"
# Exclude from processing.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

# Collections
collections:
  projects:
    output: true
  authors:
    output: true
sass:
  sass_dir: _sass
  quiet_deps: true
  style: compressed

defaults:
  - scope:
      path: ""
      type: "authors"
    values:
      layout: "author"
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"